from dataclasses import dataclass
from typing import Dict


@dataclass(frozen=True)
class GatewayResponse:
    """
    Unified response structure returned from the application to the interface layer.

    On success: wraps the upstream response (status, headers, body).
    On failure: carries a gateway-generated error status and body.

    The interface layer translates this into a FastAPI Response without
    any knowledge of whether the response came from an upstream service
    or was generated by the gateway itself.
    """

    status_code: int
    headers: Dict[str, str]
    body: bytes
